// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mock_test.go -package=memberships
//

// Package memberships is a generated GoMock package.
package memberships

import (
	context "context"
	reflect "reflect"
	memberships "xprasetio/go-account-recovery.git/internal/models/memberships"

	gomock "go.uber.org/mock/gomock"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
	isgomock struct{}
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// InitiateRecovery mocks base method.
func (m *Mockservice) InitiateRecovery(ctx context.Context, request memberships.ResetEmailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateRecovery", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateRecovery indicates an expected call of InitiateRecovery.
func (mr *MockserviceMockRecorder) InitiateRecovery(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateRecovery", reflect.TypeOf((*Mockservice)(nil).InitiateRecovery), ctx, request)
}

// Login mocks base method.
func (m *Mockservice) Login(ctx context.Context, request memberships.LoginRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, request)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockserviceMockRecorder) Login(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*Mockservice)(nil).Login), ctx, request)
}

// ResetPassword mocks base method.
func (m *Mockservice) ResetPassword(ctx context.Context, token, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, token, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockserviceMockRecorder) ResetPassword(ctx, token, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*Mockservice)(nil).ResetPassword), ctx, token, newPassword)
}

// SignUp mocks base method.
func (m *Mockservice) SignUp(ctx context.Context, request memberships.SignUpRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockserviceMockRecorder) SignUp(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*Mockservice)(nil).SignUp), ctx, request)
}

// VerifyRecoveryCode mocks base method.
func (m *Mockservice) VerifyRecoveryCode(ctx context.Context, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRecoveryCode", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRecoveryCode indicates an expected call of VerifyRecoveryCode.
func (mr *MockserviceMockRecorder) VerifyRecoveryCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRecoveryCode", reflect.TypeOf((*Mockservice)(nil).VerifyRecoveryCode), ctx, code)
}
